Presentation/MVCStore.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCStore.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

    }
}

Presentation/MVCStore.Web/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCStore.Web.Controllers
{
    public class PortfolioController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

Presentation/MVCStore.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCStore.Web.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

Presentation/MVCStore.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<div class="container">
    <hgroup class="title">
        <h1>@ViewBag.Title.</h1>
        <h2>@ViewBag.Message</h2>
    </hgroup>  
    <h2>This is a Test MVC Store Application</h2>
    <br/>
    <br/>
    <h3>Authors:</h3>
    <span class="byline">Joseph Joaquin</span> 
    <br/>
    <span class="byline">Kumar Shah</span> 
</div>

Presentation/MVCStore.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<div id="wrapper1">
    <div id="welcome" class="container">
        <div class="title">
            <h2>Welcome to our website</h2>
            <span class="byline">Do or Do Not, there is no Try.</span> </div>
        <div class="content">
            @*<p>This is <strong>Veridical</strong>, a free, fully standards-compliant CSS template designed by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>. The photos in this template are from <a href="http://fotogrph.com/"> Fotogrph</a>. This free template is released under the <a href="http://templated.co/license">Creative Commons Attribution</a> license, so you're pretty much free to do whatever you want with it (even use it commercially) provided you give us credit for it. Have fun :) </p>*@
            @*<a href="#" class="button">Etiam posuere</a> *@
            <a href="@Url.Action("Index","Product")" class="button">Products</a>
        </div>
    </div>
</div>

Presentation/MVCStore.Web/Views/Portfolio/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

    <div id="wrapper3">
        <div id="portfolio" class="container">
            <div class="title">
                <h2>Design Portfolio</h2>
                <span class="byline">Integer sit amet pede vel arcu aliquet pretium</span> </div>
            <div class="pbox1">
                <div class="column1">
                    <div class="box"> <span class="icon icon-comments"></span>
                        <h3>Vestibulum venenatis</h3>
                        <p>Fermentum nibh augue praesent a lacus at urna congue rutrum.</p>
                    </div>
                </div>
                <div class="column2">
                    <div class="box"> <span class="icon icon-cogs"></span>
                        <h3>Praesent scelerisque</h3>
                        <p>Vivamus fermentum nibh in augue praesent urna congue rutrum.</p>
                    </div>
                </div>
                <div class="column3">
                    <div class="box"> <span class="icon icon-coffee"></span>
                        <h3>Donec dictum metus</h3>
                        <p>Vivamus fermentum nibh in augue praesent urna congue rutrum.</p>
                    </div>
                </div>
                <div class="column4">
                    <div class="box"> <span class="icon icon-cloud"></span>
                        <h3>Mauris vulputate dolor</h3>
                        <p>Rutrum fermentum nibh in augue praesent urna congue rutrum.</p>
                    </div>
                </div>
            </div>
            <div class="pbox2">
                <div class="column1">
                    <div class="box"> <span class="icon icon-asterisk"></span>
                        <h3>Rhoncus volutpat</h3>
                        <p>Fermentum nibh augue praesent a lacus at urna congue rutrum.</p>
                    </div>
                </div>
                <div class="column2">
                    <div class="box"> <span class="icon icon-headphones"></span>
                        <h3>Sed odio sagittis</h3>
                        <p>Vivamus fermentum nibh in augue praesent urna congue rutrum.</p>
                    </div>
                </div>
                <div class="column3">
                    <div class="box"> <span class="icon icon-user"></span>
                        <h3>Aenean elementum</h3>
                        <p>Vivamus fermentum nibh in augue praesent urna congue rutrum.</p>
                    </div>
                </div>
                <div class="column4">
                    <div class="box"> <span class="icon icon-signal"></span>
                        <h3>Etiam posuere augue</h3>
                        <p>Rutrum fermentum nibh in augue praesent urna congue rutrum.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="wrapper2">
        <div id="featured" class="container">
            <div class="box1">
                <h2><span class="icon icon-group"></span>Fusce ultrices fringilla</h2>
                <p>Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Suspendisse dictum porta lectus. Donec placerat odio vel elit. Nullam ante orci, pellentesque eget, tempus quis, ultrices in, est. Curabitur sit amet nulla. Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum.</p>
            </div>
            <div class="box2">
                <h2><span class="icon icon-briefcase"></span>Etiam posuere augue</h2>
                <p>Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Suspendisse dictum porta lectus. Donec placerat odio vel elit. Nullam ante orci, pellentesque eget, tempus quis, ultrices in, est. Curabitur sit amet nulla. Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum.</p>
            </div>
        </div>
    </div>

Presentation/MVCStore.Web/Views/Products/Index.cshtml
@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<div class="container">
    <h2>Products..</h2>
</div>

Presentation/MVCStore.Web/Views/Shared/Copyright.cshtml
<div id="copyright">
    <div class="title">
        <h2>Get in touch</h2>
        <span class="byline">Phasellus nec erat sit amet nibh pellentesque congue</span> </div>
    <ul class="contact">
        <li><a href="#" class="icon icon-twitter"><span>Twitter</span></a></li>
        <li><a href="#" class="icon icon-facebook"><span></span></a></li>
        <li><a href="#" class="icon icon-dribbble"><span>Pinterest</span></a></li>
        <li><a href="#" class="icon icon-tumblr"><span>Google+</span></a></li>
        <li><a href="#" class="icon icon-rss"><span>Pinterest</span></a></li>
    </ul>
    <p>&copy; @DateTime.Now.Year Untitled. All rights reserved. | Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>.</p>
</div>

Presentation/MVCStore.Web/Views/Shared/Header.cshtml
<div id="header-wrapper">
    <div id="header" class="container">
        <div id="menu">
            <ul>
                <li class="current_page_item"><a href="@Url.Action("Index","Home")" accesskey="1" title="">Homepage</a></li>
                <li><a href="@Url.Action("Index","Portfolio")" accesskey="2" title="">Portfolio</a></li>
                <li><a href="@Url.Action("Index","Product")" accesskey="3" title="">Products</a></li>
                <li><a href="@Url.Action("About","Home")" accesskey="4" title="">About Us</a></li>
                <li><a href="#" accesskey="5" title="">Contact Us</a></li>
            </ul>
        </div>
        <div id="logo">
            <h1><a href="#">MVC Store</a></h1>
            @*<span>Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a></span>*@ 
        </div>
    </div>
</div>

Presentation/MVCStore.Web/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridFooter()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
        <tr class="grid-empty-text">
            <td colspan="@Model.Columns.Count()">
                @Model.EmptyGridText
            </td>
        </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
            <tr class="grid-row @Model.GetRowCssClasses(item)">
                @foreach (IGridColumn column in Model.Columns)
                {
                    @column.CellRenderer.Render(column, column.GetCell(item))
                }
            </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridFooter()
{
    <div class="grid-footer">
        @if (Model.RenderOptions.ShowGridItemsCount)
        {
            <div class="grid-itemscount">
                <span class="grid-itemscount-label">@Model.RenderOptions.GridCountDisplayName:</span>
                <span class="grid-itemscount-caption">@Model.ItemsCount</span>
            </div>
        }
        @if (Model.EnablePaging && Model.Pager != null)
        {
            @Html.Partial(Model.Pager.TemplateName, Model.Pager)
        }
    </div>
}

Presentation/MVCStore.Web/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Presentation/MVCStore.Web/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : Veridical 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20131203

-->
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>

<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet" />
<link href="~/Content/default.css" rel="stylesheet" type="text/css" media="all" />
<link href="~/Content/fonts.css" rel="stylesheet" type="text/css" media="all" />

<!--[if IE 6]><link href="default_ie6.css" rel="stylesheet" type="text/css" /><![endif]-->
</head>

    <body>
        <div id="header-wrapper">
            @Html.Partial("Header");
        </div>

        <div id="wrapper3">
            @RenderBody();
        </div>

        <div id="copyright">
            @Html.Partial("Copyright");
        </div>

    </body>
</html>